name = "QuantumGlue"
uuid = "e241dcb8-ec3d-11e8-3153-5dc0e9e220a3"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com>"]
version = "0.1.0"

[deps]
QuantumOptics = "6e0679c1-51ea-5a7c-ac74-d61b76210b0c"
Yao = "5a1af4f6-c801-11e8-08ea-1bad16a356b2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
